### PR TITLE
Add Gist support in the editor

### PR DESCRIPTION
**Pull request by Sh1d0w**
First of all I want to thank you for the great platform! I am using it for my blog and it is very cool.

Now to the PR description.

## Problem.

Currently if you want to embed a gist in your wink blog (like on medium) you have to embed it as an HTML. 

problem

This causes several problems:

1. Since for security reasons Quill does not render embed JS code, you see blank line like nothing happened after you paste the code. Moreover if you later on want to come back and edit/delete some rows, you can't see for sure if you deleted or not the row with the gist since it is not visible.
2. In FE the markup is this:

problem-html

Since it is regular html block it has class `inline_html`. This causes ...

problem-wrapping

... if you haven't set width: 100% to your `inline_html` class like I do. So either you have to set this for all `inline_html` classes or to take extra step when pasting the code into Quill and always wrap the JS with another wrapper and class that you can style differently in FE.

This is tedious.

## Solution

solution

This solves the following issues:

1. Provides nice shortcut to embed your gists.
2. Displays visual feedback in Quill (still we can't render the gist there because of restrictions), so you can see where your gist block is and format/delete it properly if required.
3. In FE we have dedicated markup now that can be styled properly and is different from `inline_html` blocks

solution-fe

### CODE REVIEW

**Comment by noxify** [comment]
@Sh1d0w Thanks for PR :) 

1. Is it possible to update an existing gist block e.g. changing the URL?
2. I didn't checked the code in detail, but are you using the default embed or is it possible to configure the output (e.g. show only line 3,5,7 etc. like https://github.com/blairvanderhoof/gist-embed )

**Comment by Sh1d0w** [comment]
@noxify Thanks!

1. No it is not currently possible, as it is not currently possible to edit an already inserted HTML code as well with the HTML block we already have. This is interesting suggestion, but given you can just remove the block and insert new one I don't think it will worth the effort.

2. No, haven't include any external dependencies. Actually I've written very minimal wrapper over the embed code that Gists provide in order to display the Gist, e.g. the JS API (https://gist.github.com/Sh1d0w/b5c3bf68ae3a903fd58825104dfb3c15.js)

The library you've posted seems neat, but has jQuery as dependency which I frankly don't like and don't think should be included in the bundle just for that purpose. I see it uses the JSON API (https://gist.github.com/Sh1d0w/b5c3bf68ae3a903fd58825104dfb3c15.json) which provides a way to customize the rendering of the Gist opposite to the JS API.

There are two possible implementations which I can do with the JSON API, but both rise different problems.

## Implement custom renderer

We will need to create a custom JS renderer for the gist on the backend and also the same renderer have to be used in the frontend. In the backend it could be a Vue component (which I am not sure can be rendered in the context of Quill?).Also Wink does not provide any default template/ui for the FE so thats tricky, it is up to the user to build the FE. 

## Pull the Gist contents directly into the post

This will solve the problem with displaying the Gist in Quill, but if you change the gist the changes won't be reflected in the post. Also again will require custom styling for FE.

Given that I think it is ok to use the default Gist renderer by simply including the JS script from the Gist as in the example screenshots.

**Comment by noxify** [comment]
Thanks for the feedback.

To 1: Yeah deleting and creating a new block is ok :)
To 2: I understand - But you're right, we should it simple and if someone need more features, they can create their own `Blot` :)

**Comment by themsaid** [comment]
Looks so good, thanks ❤️

Will have to take a deeper look, hopefully during the next couple of days and release on Sunday :)

Thanks again.

**Comment by stefanbauer** [comment]
@themsaid Any news on that PR?

**Pull request closed without merging**
