### PR TITLE
Fix Editor Output Class Name

### PR DESCRIPTION
**Pull request by finagin**
By default Quill append class `ql-syntax` but doesn't append `hlsj` and in wink package has sass for `ql-syntax` class. When you get posts from DB on frontend  you hasn't styles for `ql-syntax`, but you has `highlightjs.css` file

### CODE REVIEW

**Comment by themsaid** [comment]
I don't understand the issue you are trying to fix. Can you elaborate?

**Comment by finagin** [comment]
@themsaid, frontend needs class `hlsj` in Post::$body for support **highlightjs**

**Comment by themsaid** [comment]
Sorry I'm going to close this since code highlight is working for me already. Don't want to merge a change that could break it for people :)

**Comment by finagin** [comment]
@themsaid, how did you get the code highlighting on the frontend, not in the admin panel. Without the class attribute `hljs` it does not work

**Pull request closed without merging**
