### PR TITLE
Filter posts based on their published, scheduled and draft status

### PR DESCRIPTION
**Pull request by iamsanjit**
This PR adds filters the posts to the posts api endpoint. published, scheduled or draft draft query parameters can be used to filter the posts. 

screen recording 2018-11-17 at 10 55 25 pm

- Filter posts by adding query params(published, scheduled or draft)
- Added Select field to filter the query results

(Note: This is my very first contribution on Github, If there is any mistake, please feel free to correct me :) )

### CODE REVIEW

**Comment by bilias23** [comment]
I just logged in to implement this, this is awesome :slightly_smiling_face: 
In my opinion your implementation is a bit too complicated for something not so complex itself. Why not go for plain old scopes to the model that are easily reusable? 
Take a look at this discussion from yesterday :slightly_smiling_face: https://github.com/writingink/wink/issues/58

**Comment by themsaid** [comment]
I agree with @bilias23, You can add scopes to the model and in the controllers you can just use `Model::when` to see if there's a filter applied or not and use the proper scope. 

Do you think you can update your PR to do so?

**Comment by bilias23** [comment]
We could take a look at #64 , or rebase after merging #64 and use this?

**Comment by themsaid** [comment]
@iamsanjit  I'll merge this PR and apply the necessary changes myself. Thanks for helping, really :)

**Comment by iamsanjit** [comment]
Thank you :)

**Pull request closed without merging**
