### PR TITLE
Avoid possible SQL injection

### PR DESCRIPTION
**Pull request by ghobaty**
closes https://github.com/writingink/wink/issues/164

### CODE REVIEW

**Comment by devcircus** [comment]
I thought @themsaid fixed this on the Laravel side, so this would no longer be an issue, but I may be mistaken.

**Comment by devcircus** [comment]
If we go this route, every update/store call will hit the database twice with a select query. Actually there would be three queries now, as the unique rule hits the database as well.

I would recommend moving the following line
```php
$entry = $id !== 'new' ? WinkPost::findOrFail($id) : new WinkPost(['id' => request('id')]);
```
 
above the validation, then changing:
 ```php
Rule::unique(config('wink.database_connection').'.wink_posts', 'slug')->ignore(request('id')),
        ])->validate()
```

to:
```php
Rule::unique(config('wink.database_connection').'.wink_posts', 'slug')->ignore($entry->id),
        ])->validate()
```

This way we avoid two select queries every time and also prevent the possibility of sql injection (if that hasn't already been fixed in the framework.)

**Comment by ghobaty** [comment]
I didn’t know about the framework fox itself! But if this is still needed, I agree with your suggested solutions.

**Comment by themsaid** [comment]
thanks and sorry for the delay :)

**Pull request closed without merging**
