### PR TITLE
Add Language and Category.

### PR DESCRIPTION
**Pull request by aliqasemzadeh**

### CODE REVIEW

**Comment by ghost** [comment]
Fixes, Release this update

**Comment by aliqasemzadeh** [comment]
@Arsivpro 
How can I solve this problem?

**Comment by ghost** [comment]
@alighasemzadeh As far as I understand there is no error and the works are without problems,
you can cancel the pull request with a reconfiguration and try again

**Comment by sajaddp** [comment]
@alighasemzadeh Why did you change the information in the "composer.json" file?

**Pull request closed without merging**
