### PR TITLE
Add bootstrap and popper.js dependencie, yarn.lock update

### LINKED ISSUE #52: Error when compiling assets
After running `yarn run dev` or `npm run dev`, it seems that 2 dependencies are missing: **Bootstrap** and **Popper.js**.  They way to get around this is to install them manually. I think the problem is that they are not declared on the `package.json`file.

### PR DESCRIPTION
**Pull request by skoyah**
This PR fixes #52 .

### CODE REVIEW

**Comment by lucasmichot** [comment]
@skoyah - should you not also commit the updated version of `yarn.lock` then?

**Comment by skoyah** [comment]
@lucasmichot I'm kinda new when it comes to contributing, so I wasn't sure if the lock files should be committed to packages. Should I commit them?

**Comment by skoyah** [comment]
Ok @lucasmichot! Thanks for the info! Will do it asap!

**Comment by skoyah** [comment]
So @lucasmichot one more thing, how can I add the yarn.lock file to this PR? or should I delete this PR and create a new one?

**Comment by themsaid** [comment]
But we're not using Bootstrap anymore. We use TailwindCSS now.

**Comment by skoyah** [comment]
So that begs the question of maybe removing the unnecessary call to bootstrap an popper.js on the app.js file.

**Pull request closed without merging**
