### PR TITLE
Laravel 9 Support

### LINKED ISSUE #353: Latest Laravel 9 php 8.1
Will /wink be upgraded at any point? as its still using require php ^7.3||^7.4 so i cant use Wink on laravel 9 php 8.1

### PR DESCRIPTION
**Pull request by swapnilsarwe**
* Bumped the version to laravel 9 (Fixes #353 )

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@swapnilsarwe thanks for this! Have you tested in a wink project?

**Comment by swapnilsarwe** [comment]
@lukeraymonddowning i did test it on my personal blog, and its working fine.

**Comment by swapnilsarwe** [comment]
Should we add some very basic tests in the package, just to be sure for any major upgrades in the future. Coz' even I was sceptical to upgrade on personal blog, but changes just worked fine, without any hiccups.

**Comment by lukeraymonddowning** [comment]
Yeah, we need to flesh out the test suite. I added Pest in a recent PR, so we should be able to at least test the major areas. Would make upgrades a little easier to make.

**Comment by swapnilsarwe** [comment]
> Yeah, we need to flesh out the test suite. I added Pest in a recent PR, so we should be able to at least test the major areas. Would make upgrades a little easier to make.

@lukeraymonddowning  I am going to cherry pick pest configuration from your PR #348 , and add to this PR with the tests which I think make sense. @themsaid you can give your inputs on the same whenever you get time - no rush.

**Comment by KDA809** [comment]
when do prs get merged

**Comment by swapnilsarwe** [comment]
> when do prs get merged

Have patience.
You can use referenced repo, if you are in a hurry as follows

```
{
    "repositories": [
        ...,
        {
            "type": "vcs",
            "url": "https://github.com/swapnilsarwe/wink.git"
        }
    ]
},
{
    "require": {
       ...,
        "themsaid/wink": "dev-laravel9",
    }
```

**Pull request merged**
