### PR TITLE
Feature/create admin account

### PR DESCRIPTION
**Pull request by abr4xas**
Offer ease of entering our credentials as an admin user when running migration

### CODE REVIEW

**Comment by themsaid** [comment]
I was thinking. Instead of creating the first Author in an artisan command, it might be better to let the user create it from the interface.

So if the wink_authors table is empty, when you head to `yourapp.com/wink` or whatever path you chose for wink, if the table is empty you get redirected to `/install` instead of `/login`.

From there you can create your first user.

Can you convert that PR to be UI based?

**Comment by Lloople** [comment]
It would look great in a UI, but maybe is a bit overkill for this package? 

I mean, comparing the number of times a user will see the install screen... maybe if that screen is used for more configuration, like Wordpress does 🤔

**Comment by themsaid** [comment]
@Lloople I don't see it as an overkill TBH, people are confused by the migrate command creating a new user and the often don't notice the credentials. So driving them to a UI provides a much clearer communication.

**Comment by abr4xas** [comment]
OK, I'm working on this!!

**Comment by themsaid** [comment]
Hey @abr4xas, are you still going to work on this or should I tackle it?

**Comment by abr4xas** [comment]
Sorry man, i dont have time to do this :( take it!!

**Comment by themsaid** [comment]
@abr4xas no problem.

**Pull request closed without merging**
