### PR TITLE
Add tag description field

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by themsaid** [comment]
Not sure I understand why this can be useful. Can you share some thoughts?

**Comment by assertchris** [comment]
I wanted to show a list of tags on my home page, and describe the kind of content that would be in posts of that tag. I could show the content of a single post, but that wouldn’t be representative of the whole tag. This seemed like a potential solution to that problem.

Having said that; what’s to stop someone wanting an image upload field as well..?

**Comment by itainathaniel** [comment]
@assertchris you want wink to be more like Wordpress?
image

**Comment by assertchris** [comment]
@itainathaniel If WordPress caters to the exact scenario I described, then sure. I'm not using WordPress as a guide, though. I'm not sure how the comparison helps this discussion...

**Comment by itainathaniel** [comment]
@assertchris I think WordPress caters many or most scenarios, this could explain its popularity. It might help the discussion by showing that other widely-used blogging platform is doing the same thing you try to do here.

**Pull request closed without merging**
